### ISSUE TITLE
Hash-bang de montar_server.sh

### ISSUE THREAD

**Issue by dualbus** [gultij/alternus.gultij.org#7]
Solo un pequeño nit-pick:

El hash-bang es:

`#!<ruta>`

`#<espacio>!` es un hash-bang inválido.

Además, bash usualmente está en /bin/bash, no en /usr/bin/bash.

Pero lo que sugiero es cambiarlo a /bin/sh, para mejorar la portabilidad, y porque no estamos usando algún feature específico de bash como para requerirlo. De todos modos, al tener un hash-bang inválido -que es el caso actual- la mayoría de los SOs suponen que es un script /bin/sh

**Comment by gatopanx** [comment]
Thanks for the feedback! I've sent a new pr addressing this issue: https://github.com/gultij/alternus.gultij.org/pull/8

**Comment by alvarezp** [comment]
Gracias a ambos! -- Thanks both!
